#! /bin/sh
#chkconfig:  2345 81 96
#description: start postgresql

# path: /etc/init.d/postgresqld
# description: process postgresql node service
# processname: kongd

SERVICE_USER_NAME=SOFTWARE_USER_NAME

case "$1" in
    start)
		systemctl start postgresql-11
    ;;
	stop)
		systemctl stop postgresql-11
    ;;
	restart)
	    systemctl restart postgresql-11
    ;;
	status)
		systemctl status postgresql-11
	;;
esac

