#! /bin/sh
#chkconfig:  2345 81 96
#description: start rocketmq

# path: /etc/init.d/rocketmqd
# description: process rocketmq service
# processname: rocketmqd

SERVICE_USER_NAME=SOFTWARE_USER_NAME
SERVICE_INSTALL_PATH=SOFTWARE_INSTALL_PATH
ROCKETMQ_NAME_SERVER_PROCESS_NAME=NamesrvStartup
ROCKETMQ_BROKER_SERVER_PROCESS_NAME=BrokerStartup
ROCKETMQ_LOCAL_IP=127.0.0.1
ROCKETMQ_NAME_SERVER_HOST_INFO='127.0.0.1:9876'

case "$1" in
    start)
        if [ "${2}" == "nameserver" ]; then
            process_id=`ps -ef|grep -i "${ROCKETMQ_NAME_SERVER_PROCESS_NAME}" |grep -v "grep"|awk '{print $2}'`
            if [ -z "${process_id}" ];then
                echo "Starting service..."

                su - ${SERVICE_USER_NAME}  -c "nohup ${SERVICE_INSTALL_PATH}/bin/mqnamesrv -n ${ROCKETMQ_LOCAL_IP} 1>/dev/null 2>/dev/null & "

                sleep 2
                process_id=`ps -ef|grep -i "${ROCKETMQ_NAME_SERVER_PROCESS_NAME}" |grep -v "grep"|awk '{print $2}'`
                if [ -z "${process_id}" ];then
                    echo "Start service error!"
                    exit 1
                else
                    echo "Start service success!"
                fi
            else
                echo "Service is running!"
            fi
        elif [ "${2}" == "brokerserver" ]; then
            process_id=`ps -ef|grep -i "${ROCKETMQ_BROKER_SERVER_PROCESS_NAME}" |grep -v "grep"|awk '{print $2}'`
            if [ -z "${process_id}" ];then
                echo "Starting service..."

                if [ "${3}" == "master" ]; then
                    if [ "${4}" == "1" ]; then
                        su - ${SERVICE_USER_NAME}  -c "nohup ${SERVICE_INSTALL_PATH}/bin/mqbroker -c ${SERVICE_INSTALL_PATH}/conf/2m-2s-sync/broker-a.properties -n '${ROCKETMQ_NAME_SERVER_HOST_INFO}' 1>/dev/null 2>/dev/null & "
                    else
                        su - ${SERVICE_USER_NAME}  -c "nohup ${SERVICE_INSTALL_PATH}/bin/mqbroker -c ${SERVICE_INSTALL_PATH}/conf/2m-2s-sync/broker-b.properties -n '${ROCKETMQ_NAME_SERVER_HOST_INFO}' 1>/dev/null 2>/dev/null & "
                    fi
                else
                    if [ "${4}" == "1" ]; then
                        su - ${SERVICE_USER_NAME}  -c "nohup ${SERVICE_INSTALL_PATH}/bin/mqbroker -c ${SERVICE_INSTALL_PATH}/conf/2m-2s-sync/broker-a-s.properties -n '${ROCKETMQ_NAME_SERVER_HOST_INFO}' 1>/dev/null 2>/dev/null & "
                    else
                        su - ${SERVICE_USER_NAME}  -c "nohup ${SERVICE_INSTALL_PATH}/bin/mqbroker -c ${SERVICE_INSTALL_PATH}/conf/2m-2s-sync/broker-b-s.properties -n '${ROCKETMQ_NAME_SERVER_HOST_INFO}' 1>/dev/null 2>/dev/null & "
                    fi
                fi

                sleep 2
                process_id=`ps -ef|grep -i "${ROCKETMQ_BROKER_SERVER_PROCESS_NAME}" |grep -v "grep"|awk '{print $2}'`
                if [ -z "${process_id}" ];then
                    echo "Start service error!"
                    exit 1
                else
                    echo "Start service success!"
                fi
            else
                echo "Service is running!"
            fi
        fi
    ;;
	stop)
		echo "Shutting down service..."
		if [ "${2}" == "nameserver" ]; then
            process_id=`ps -ef|grep -i "${ROCKETMQ_NAME_SERVER_PROCESS_NAME}" |grep -v "grep"|awk '{print $2}'`
            if [ -z "${process_id}" ];then
                echo "There is no service running!"
            else
                kill -9 ${process_id}
                echo "Service " ${process_id} " is killed!"
            fi
        elif [ "${2}" == "brokerserver" ]; then
            process_id=`ps -ef|grep -i "${ROCKETMQ_BROKER_SERVER_PROCESS_NAME}" |grep -v "grep"|awk '{print $2}'`
            if [ -z "${process_id}" ];then
                echo "There is no service running!"
            else
                kill -9 ${process_id}
                echo "Service " ${process_id} " is killed!"
            fi
        fi
        echo "Service stop success!"
    ;;
	restart)
        $0 stop ${2}
        sleep 5
        $0 start ${2} ${3} ${4}
    ;;
	status)
		su - ${SERVICE_USER_NAME}  -c "${SERVICE_INSTALL_PATH}/bin/mqadmin consumerStatus -n '${ROCKETMQ_NAME_SERVER_HOST_INFO}' "
	;;
esac

